"""
1. Write a flask server endpoint using GET method
    /weather?days=<days>&zip_code=<zip_code>
   It returns the response
   {
       "<date1>" :  {
            "condition": "<condition>",
            "condition_img": "<condition image url>",
            "min_temperature": "<lowest temperature of the day>",
            "max_temperature": "<highest temperature of the day>"
       }
      "<date2>": ....
   }

   Namely
    /weather?days=1&zip_code=94568
   It should return
    {
        "2026-04-01": {
             "condition": "Rainy",
             "condition_img": "http://cdn.weatherapi.com/weather/64x64/night/122.png&quot;,
             "min_temperature": "80F",
              "max_temperature": "100F"
         }
   }

   In case something is wrong, return error code 500 with Error message. No Server Crash!

"""


"""
2. Write a flask server endpoint using POST method
   /generate_story
   with body
  [
{"data_url": "<data_url of image 1>", "description": "<description 1>"},
{"data_url": "<data_url of image 2>", "description": "<description 2>"},
....
  ]

   It returns the response
   {
      "story": "<the story generated by LLM based on input>"
   }

In case things go wrong, server should not crash, but return error message with error code 400
"""

import os
import re
import requests
from google import genai
from google.genai import types
from dotenv import load_dotenv

# dotenv -f /path/to/.env run python3 app.py
load_dotenv() # load from .env by default in the current directory
    
import json
from flask import Flask, request

MODEL = "gemini-2.5-flash-lite" 

client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

app = Flask(__name__)

# /weather?days=<days>&zip_code=<zip_code>
@app.route('/weather')
def weather_handler():
    try:
        days = request.args.get('days')
        zip_code = request.args.get('zip_code')
        api_key = os.environ['WEATHER_API_KEY']
        
        response = requests.get(f"http://api.weatherapi.com/v1/forecast.json?key={api_key}&q={zip_code}&days={days}")
        
        response_obj = json.loads(response.content)
        result = {}
        for day_report in response_obj["forecast"]["forecastday"]:
            date = day_report["date"]
            condition = day_report["day"]["condition"]["text"]
            condition_img = day_report["day"]["condition"]["icon"]
            min_temp = f'{day_report["day"]["mintemp_f"]}F'
            max_temp = f'{day_report["day"]["maxtemp_f"]}F'
            
            result[date]={
                "condition": condition,
                "condition_img": condition_img,
                "min_temperature": min_temp,
                "max_temperature": max_temp,
            }
        
        return json.dumps(result), 200
    except Exception as e:
        return json.dumps({"error": str(e)}), 500
    



def data_url_to_google_types(data_url):
    _, media_type, encode_base, content = re.split("data:|;|,", data_url)
    return types.Part.from_bytes(
        mime_type=media_type,
        data=content,
    )


"""
example of input:
[
{"data_url": "<data_url of image 1>", "description": "<description 1>"},
{"data_url": "<data_url of image 2>", "description": "<description 2>"},
....
  ]

"""
def make_story(image_url_obj):
    try:
        contents = [
            """
            Make up a story based on the input images, and also consider the corresponding description provided.
            Please limit your response within 100 words.
            """
        ]
        
        i = 0
        for image_with_desc in image_url_obj:
            i+=1
            contents.append(data_url_to_google_types(image_with_desc["data_url"]))
            contents.append(f"The {i}-th image's description: {image_with_desc['description']}")
   
        response = client.models.generate_content(
            model = MODEL,
            contents=contents,
        )
        
        return {
            "story": response.text
        }
    except Exception as e:
        return {
            "error": f"Exception occured: {e}"
        }
        

@app.route('/generate_story', methods=['POST'])
def generate_story():
    image_url_obj = json.loads(request.data)
    print(image_url_obj)
    value = json.dumps(make_story(image_url_obj))
    print(value)
    return value, 200

if __name__ == '__main__':
    app.run(debug=True)